application: your-app-id
version: 1
runtime: python
api_version: 1

handlers:
- url: /blog/static
  static_dir: static

- url: /blog/admin.*
  script: blog.py
  login: admin

- url: /blog.*
  script: blog.py

# If GAE Blog is a submodule then you need to copy these handlers to your own app.yaml
# and modify their paths to include where the directory where GAE Blog is located.
# Assuming it's in a directory called "gae_blog", they should look like this:
#
# - url: /blog/static
#   static_dir: gae_blog/static
#
# - url: /blog/admin.*
#   script: gae_blog/blog.py
#   login: admin
#
# - url: /blog.*
#   script: gae_blog/blog.py

